### ISSUE TITLE
how to use BlackboardQuery ? I get confused. I need example, please.

### ISSUE THREAD

**Issue by myselfshj** [meniku/NPBehave#11]
Hello author!
Thanks for your sharing program first.
 
I tried to modifyEnemyAI example. I tried BlackboardQuery in Selector, like this:
new BlackboardQuery(keys, Stops.IMMEDIATE_RESTART, MyBoardQuery, new Sequence());

keys assigned like this:
private string[] keys = new string[2];
keys[0] = "OrcDistance";         //if Orc is near, run away. 
keys[1] = "goblinDistance";      //if goblin is near, attack. both conditions should query simultaneously.

MyBoardQuery() method is defined like this:
    private bool MyBoardQuery()
    {
        object o1 = behaviorTree.Blackboard.Get(keys[0]);
        object o2 = behaviorTree.Blackboard.Get(keys[1]);
        float f1 = (float)o1;
        float f2 = (float)o2;

        if ((f1 > 0.99) && (f2 < 5.99f))
            return true;
        return false;
    }

but I get errors in Unity :
Assertion failed. Value was False
Expected: True
UnityEngine.Assertions.Assert:IsTrue(Boolean)
NPBehave.Composite:.ctor(String, Node[]) (at Assets/NPBehaveTest01/NPBehave/Scripts/Composite/Composite.cs:12)
NPBehave.Sequence:.ctor(Node[])
NPBehaveExampleEnemyAI:CreateBehaviourTree() (at Assets/NPBehaveTest01/NPBehave/Examples/Scripts/NPBehaveExampleEnemyAI.cs:32)
NPBehaveExampleEnemyAI:Start() (at Assets/NPBehaveTest01/NPBehave/Examples/Scripts/NPBehaveExampleEnemyAI.cs:13)

ArgumentNullException: Argument cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.List`1[System.Action`2[NPBehave.Blackboard+Type,System.Object]]].ContainsKey (System.String key) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:458)

can only stop active nodes, tried to stop Sequence! PATH: Root/Service/Selector/BlackboardCondition/Sequence
Assertion failed. Values are not equal.
Expected: ACTIVE == INACTIVE
UnityEngine.Assertions.Assert:AreEqual(State, State, String)
NPBehave.Node:Stop() (at Assets/NPBehaveTest01/NPBehave/Scripts/Node.cs:111)

IndexOutOfRangeException: Array index is out of range.
NPBehave.Sequence.DoStop () (at Assets/NPBehaveTest01/NPBehave/Scripts/Composite/Sequence.cs:29)
NPBehave.Node.Stop () (at Assets/NPBehaveTest01/NPBehave/Scripts/Node.cs:117)

What's wrong ? Can you kindly enough to give an example of  BlackboardQuery?

**Comment by meniku** [comment]
Your `BlackboardQuery` looks good, the source of the exception comes from the empty `Sequence()` I guess.
All composites (`Selector`,  `Sequence` and `Parallel`) require at least one child right now.

Just replace the `new Sequence()` by `new Sequence ( new Wait (0.5f) )` an the first error should go away. Probably the following errors too, but I'm not sure.

**I need to add an assertion message to make that more clear in the future.**

I rarley used the `BlackboardQuery` yet, but I found a occurrence in one of my AIs, maybe if that helps:

```
    private static string BK_POWERUP_TYPE = "powerupType";

    ...

    protected Node createSwapperCannonTree()
    {
        return new BlackboardQuery( new string[] {BK_POWERUP_TYPE}, Stops.IMMEDIATE_RESTART, () => behavior.Blackboard.Get<PowerupType>(BK_POWERUP_TYPE) == PowerupType.TARGET_SWAPPER || behavior.Blackboard.Get<PowerupType>(BK_POWERUP_TYPE) == PowerupType.TELEPORT,  
            new Sequence(
                ...
            )
        ) {Label = " Swapper / Cannon", Collapse = true};
    }

```
*NOTE: createSwapperCannonTree() is not the full tree, it's called while building the full behavior tree.*

**Comment by myselfshj** [comment]
It works now. the reason of failure is keys not assigned value correctly, it 's empty that make errors.
I assigned keys value in Start() of Unity, it didn't work. Now I assigned keys value in UpdatePlayerDistance() of service, it works.
Great ! 
I am testing more functions.

**Comment by meniku** [comment]
oh I see, 
you probably also got a NullReferenceException, because you were doing this:

```                
object o1 = behaviorTree.Blackboard.Get("key1");
object o2 = behaviorTree.Blackboard.Get("key2");
float f1 = (float)o1;
float f2 = (float)o2;
```

`Get` will return null if there is no value for the key.

You could also use the `Get<float>("key1")` which would have returned 0.0f in case the key wouldn't have existed.

But having a service setting the keys is good practice anyway

**Comment by meniku** [comment]
I'm assuming this is solved now?

**Comment by myselfshj** [comment]
Yes, this is solved. Thanks.
