### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by slimshader** [meniku/NPBehave#16]
Hey, is this library still maintained? Unity 2018/2019 supported?

**Comment by meniku** [comment]
Sure the library is still maintained. If you have troubles to make it run in a newer version let me know and I'll fix it. I don't check every Unity version for compatibility by myself as I'm currently not using unity much.

**Comment by AStrayWitch** [comment]
I can confirm that it works in Unity 2019.3.0a2

**Comment by meniku** [comment]
Ok thx, just be sure to use the version from github, I didn't update the store version for a while.
