### ISSUE TITLE
BlackboardCondition seems can't stop lower priority repeater node when using a child blackboard

### ISSUE THREAD

**Issue by ghost** [meniku/NPBehave#17]
At first using the default blackboard and BlackboardCondition, it works. And then try to move the code into a node factory and use a shared blackboard. After some trial and error, found that if use a BlackboardCondition node and with a none default child board, even if set it to IMMEDIATE_RESTART and the condition is meet, the state would stuck in a lower priority repeater node, and swtich BlackboardCondition node to condition node, it works agin.

**Comment by meniku** [comment]
Can you send me some example code/project so I can reproduce the issue?

**Comment by meniku** [comment]
OK I managed to reproduce & fix it relatively easy. 
The issue was related to the child blackboard not being properly notified when a value was changed in the parent blackboard (and shouldn't be related to the `Repeater` node).

Let me know if you still have issues.

Thanks for the report!
