### ISSUE TITLE
[Question] Clock timer with repetitions

### ISSUE THREAD

**Issue by josencv** [meniku/NPBehave#20]
I have a question about the clock behavior when used with repetitions. Don't know if it's intended behavior or not.

If I add a timer with a time of X seconds with repeats, the first time it waits X seconds, but after that it repeats every tick. Seeing your [NavMoveTo](https://github.com/meniku/NPBehave/blob/master/Scripts/Task/NavMoveTo.cs) script, I thought the time parameter was meant to be the update frequency.

I could solve the problem by adding a timer with no repeats every time the action is called, but if this is an issue, I'd rather fix this.

I'm using Unity 2019.2.01f and NPBehave latest version.

**Comment by meniku** [comment]
this sounds like a bug, I think I can find some time at Monday to check

**Comment by josencv** [comment]
Thanks! If you need more info, I'll be happy to share.

**Comment by meniku** [comment]
This was an implementation oversight, I fixed it. Thanks a lot for the report!
