### ISSUE TITLE
Assertion in Wait action

### ISSUE THREAD

**Issue by slimshader** [meniku/NPBehave#24]
I am getting an assertion exception from within the Wait node in the Stop() method:
```
Assert.AreEqual(this.currentState, State.ACTIVE, "can only stop active nodes, tried to stop");
```

The node is nested under Condition with Stops.IMMEDIATE_RESTART

**Comment by meniku** [comment]
hey thanks for the report, can you somehow provide try to provide an example script where I can reproduce it on my side?
