### ISSUE TITLE
Null check on Condition node works but not on BlackboardCondition node

### ISSUE THREAD

**Issue by Hobilsm** [meniku/NPBehave#26]
Hello, i am making a space fight game and i am using NPBehave to implement AI, however i encountered this weird issue.

So basically there is a "Target" entry in my blackboard and if it is null i want to select a new target, which i implemented as these:

```C#
new BlackboardCondition("Target", Operator.IS_EQUAL, null, Stops.IMMEDIATE_RESTART,

    new Action(() => SelectANewTarget())

)
```
and
```C#
new Condition(() => Target == null, Stops.IMMEDIATE_RESTART,

    new Action(() => SelectANewTarget())

)
```
Target value is GameObject, and i am destroying the ships with Destroy(gameobject). So when target ship is destroyed these implementations suppose to stop the lower nodes and start itself. While implementation with Condition node works implementation with BlackboardCondition does not work.

My test scene starts with every ship having null value for Target so when scene starts every ship finds a target, the thing is BlackboardCondition actually does it's job once, meaning that ships can take find their first target, but once that target is destroyed BlackboardCondition node doesnt restart itself. So i am guessing BlackboardCondition node cant observe that the value has changed.

**Comment by Hobilsm** [comment]
I am using a notification system that allows me to notify all ships when one of the ships is about to be destroyed. So that was i can null the references to that ship so blackboard can actually track it. So i guess in order for blackboard to work you need to set the values using blackboard.

**Comment by meniku** [comment]
I've reopened the issue as I really would like to see if there is some solution. The blackboard uses dictionaries under the hood. I think it's strange that member variables are apparently automatically nulled when he component is destroyed, while the dictionary entry doesn't. 

Anyway I would like to investigate this first before closing it.
