### ISSUE TITLE
Debugger Window not scrollable on OSX

### ISSUE THREAD

**Issue by meniku** [meniku/NPBehave#8]
@Xerios Do you have an idea about this? The scrollbar is visible but there is no way of scrolling it. When clicking the "down" arrow it scrolls for 1 frame but immediately snaps back again

**Comment by Xerios** [comment]
RIght, had this one as well recently. You simply need to set `scrollPosition = EditorGUILayout.BeginScrollView(scrollPosition);`

I made a PR.
Gonna push some other visual changes to the tree too, just checked it out and realized that it doesn't look too good on the eyes with all those darkish colors.

**Comment by meniku** [comment]
OH that's great, thanks :)
